### ISSUE TITLE
watchman doesn't capture changes in host files

### ISSUE THREAD

**Issue by mvayngrib** [rnplay/react-native-packager-docker#1]
for me it seems watchman doesn't react to changes in files on the host (index.ios.js, etc.). Is this just my build or does this happen for you as well?

**Comment by jsierles** [comment]
This is working for us on the React Native Playground. What's your docker version and watchman version?

**Comment by mvayngrib** [comment]
Docker version 1.7.1, build 786b29d
watchman: 3.1.0

**Comment by jsierles** [comment]
are you making changes inside the docker container or in a mounted volume?

**Comment by mvayngrib** [comment]
good q, not in the container, let me see if that makes a diff

**Comment by jsierles** [comment]
I'm using this on a Ubuntu 14.04 host.

**Comment by mvayngrib** [comment]
k, so it works if I do it with docker exec ... sed -i ... (replace some string)
but not if I just edit it on my Mac in Sublime (Yosemite 10.10.4)

**Comment by jsierles** [comment]
Ah, on a Mac you need to also share your local volume with the docker host. If you use boot2docker, here are some instructions on how you might do that:

https://github.com/boot2docker/boot2docker#folder-sharing

**Comment by mvayngrib** [comment]
awesome, will try and report success. Thanks!

**Comment by mvayngrib** [comment]
I ended up going with [docker-osx-dev](https://github.com/brikis98/docker-osx-dev). Works well so far.

**Comment by jsierles** [comment]
Looks good! I'll add to docs.
